name: Build and Release

on: release

jobs:
  build:
    name: Build and Release go temporal lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22.1

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      # Build
      - name: Build linux/amd64
        run: GOARCH=amd64 GOOS=linux go build -v -o go-temporal-lint-linux-amd64

      - name: Build linux/arm64
        run: GOARCH=arm64 GOOS=linux go build -v -o go-temporal-lint-linux-arm64

      - name: Build darwin/amd64
        run: GOARCH=amd64 GOOS=darwin go build -v -o go-temporal-lint-darwin-amd64

      - name: Build darwin/arm64
        run: GOARCH=arm64 GOOS=darwin go build -v -o go-temporal-lint-darwin-arm64

      # compress
      - name: Compress linux/amd64
        run: tar -czvf go-temporal-lint-linux-amd64.tar.gz go-temporal-lint-linux-amd64

      - name: Compress linux/arm64
        run: tar -czvf go-temporal-lint-linux-arm64.tar.gz go-temporal-lint-linux-arm64

      - name: Compress darwin/amd64
        run: tar -czvf go-temporal-lint-darwin-amd64.tar.gz go-temporal-lint-darwin-amd64

      - name: Compress darwin/arm64
        run: tar -czvf go-temporal-lint-darwin-arm64.tar.gz go-temporal-lint-darwin-arm64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset linux/amd64
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-temporal-lint-linux-amd64.tar.gz
          asset_name: go-temporal-lint-linux-amd64.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload Release Asset linux/arm64
        id: upload_release_asset_linux_arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-temporal-lint-linux-arm64.tar.gz
          asset_name: go-temporal-lint-linux-arm64.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload Release Asset darwin/amd64
        id: upload_release_asset_darwin_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-temporal-lint-darwin-amd64.tar.gz
          asset_name: go-temporal-lint-darwin-amd64.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload Release Asset darwin/arm64
        id: upload_release_asset_darwin_arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-temporal-lint-darwin-arm64.tar.gz
          asset_name: go-temporal-lint-darwin-arm64.tar.gz
          asset_content_type: application/octet-stream